exclude: >
  (?x)(
    ^setup/|
    /cassettes/|
    \.pot$|
    \.po$|
    /README.rst$|
    ^(
      # installable = False
      partner_contact_company|
      product_online_category|
      product_stock_state|
      shopinvader_backend_image_proxy|
      shopinvader_contact_company|
      shopinvader_custom_attribute|
      shopinvader_demo_app|
      shopinvader_guest_mode|
      shopinvader_invoice|
      shopinvader_locomotive_contact_company|
      shopinvader_locomotive_elasticsearch|
      shopinvader_locomotive_reset_password|
      shopinvader_multi_category|
      shopinvader_partner_vat|
      shopinvader_pending_cart_reminder|
      shopinvader_product_media|
      shopinvader_product_new|
      shopinvader_product_stock_assortment|
      shopinvader_product_stock|
      shopinvader_product_stock_state|
      shopinvader_promotion_rule|
      shopinvader_quotation|
      shopinvader_sale_profile|
      shopinvader_sale_report
    )/
  )
repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    args: [--line-length=79, --safe]
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: fix-encoding-pragma
    args: ["--remove"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    name: flake8 except __init__.py
    args: [--exclude=__init__.py]
    language_version: python3
  - id: flake8
    name: flake8 only __init__.py
    args: [--extend-ignore=F401]  # ignore imported unused in __init__.py
    files: __init__.py
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.3.1
  hooks:
    - id: pylint
      name: pylint with optional checks
      args: ["--rcfile=.pylintrc", "--exit-zero"]
      verbose: true
      additional_dependencies: ["pylint-odoo==3.1.0"]
    - id: pylint
      name: pylint with mandatory checks
      args: ["--rcfile=.pylintrc-mandatory"]
      additional_dependencies: ["pylint-odoo==3.1.0"]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.6.1
  hooks:
  - id: pyupgrade
    language_version: python3
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.3.0
  hooks:
  - id: seed-isort-config
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    language_version: python3
